//
//  AppConstants.h
//  crisscross
//
//  Created by Vincent Tuscano on 4/17/15.
//  Copyright (c) 2015 RAVN. All rights reserved.
//

#define API_CLIENT_VERSION 301.0
#define API_VERSION_NUMBER 2

#define kTestingMode NO

#define kEnvironment 1

#if kEnvironment == 1
#define WEB_SERVICE_ROOT @"https://m.crisscrosstheapp.com/api/"
#define WEB_SERVICE_FILES_DIR @"http://-/files/"
#endif

#define IMAGE_PATH @"https://d1mgyibb2exily.cloudfront.net/assets/img/"

#if kEnvironment == 2
#define WEB_SERVICE_ROOT @"http://ravn.crisscross/api/"
#define WEB_SERVICE_FILES_DIR @"http://-/files/"
#endif

#define FONT_ICONS @"crisscrossfont"

#define kImageAlpha 0.12 
#define FONT_HELVETICA_NEUE_BOLD @"HelveticaNeue-Bold"
#define FONT_HELVETICA_NEUE_MED @"HelveticaNeue-Medium"
#define FONT_HELVETICA_NEUE_LIGHT @"HelveticaNeue-Light"
#define FONT_HELVETICA_NEUE_THIN @"HelveticaNeue-Thin"
#define FONT_HELVETICA_NEUE_ULTRA_LIGHT @"HelveticaNeue-UltraLight"
#define FONT_HELVETICA_NEUE @"HelveticaNeue"
#define COLOR_CC_GREEN @"#30C720"
#define COLOR_CC_TEAL @"#00DBFF"
#define COLOR_CC_BLUE @"#005AE8"


#define COLOR_CC_RED @"#E04247"
#define COLOR_CC_BLUE_BG @"#000044"
#define COLOR_CC_BLUE_BG2 @"#010C55"


#define COLOR_GREEN @"#36CB31"

#define NOTIFICATION_ENTERED_FOREGROUND @"NOTIFICATION_ENTERED_FOREGROUND"
#define NOTIFICATION_ENTERED_BACKGROUND @"NOTIFICATION_ENTERED_BACKGROUND"
#define NOTIFICATION_PUSH_RECEIVED @"NOTIFICATION_PUSH_RECEIVED"
#define NOTIFICATION_SENT_FROM_NOTIFICATIONS @"NOTIFICATION_SENT_FROM_NOTIFICATIONS"
#define NOTIFICATION_USER_INFO_UPDATED @"NOTIFICATION_USER_INFO_UPDATED"
#define NOTIFICATION_USER_GROUPS_UPDATED @"NOTIFICATION_USER_GROUPS_UPDATED"
#define NOTIFICATION_PLANS_UPDATED @"NOTIFICATION_PLANS_UPDATED"
#define NOTIFICATION_DASH_ANIMATE_IN @"NOTIFICATION_DASH_ANIMATE_IN"
#define NOTIFICATION_BEEN_THERE_ADJUST_LAYOUT @"NOTIFICATION_BEEN_THERE_ADJUST_LAYOUT"
#define NOTIFICATION_ADD_BEEN_THERE_ITEM @"NOTIFICATION_ADD_BEEN_THERE_ITEM"
#define NOTIFICATION_DELETE_BEEN_THERE_CHILD @"NOTIFICATION_DELETE_BEEN_THERE_CHILD"
#define NOTIFICATION_ADD_BEEN_THERE_ITEM_RELOAD @"NOTIFICATION_ADD_BEEN_THERE_ITEM_RELOAD"
#define NOTIFICATION_REFRESH_WELCOME_SCREEN @"NOTIFICATION_REFRESH_WELCOME_SCREEN"
#define NOTIFICATION_FOR_FIND_SHOW_HERE @"NOTIFICATION_FOR_FIND_SHOW_HERE"
#define NOTIFICATION_REFRESH_ACTIVITY @"NOTIFICATION_REFRESH_ACTIVITY"
#define NOTIFICATION_REFRESH_DREAMING_OF @"NOTIFICATION_REFRESH_DREAMING_OF"
#define NOTIFICATION_FOR_REFRESH_FIND @"NOTIFICATION_FOR_REFRESH_FIND"
#define NOTIFICATION_BTDT_DO_HIDE_SEARCH_CAUSE_OF_SCROLL @"NOTIFICATION_BTDT_DO_HIDE_SEARCH_CAUSE_OF_SCROLL"
#define NOTIFICATION_PLAN_CONFLICT_ITEM @"NOTIFICATION_PLAN_CONFLICT_ITEM"
#define NOTIFICATION_RELOAD_USER_INFO @"NOTIFICATION_RELOAD_USER_INFO"
#define NOTIFICATION_EMAIL_OR_SMS_INVITE_SENT @"NOTIFICATION_EMAIL_OR_SMS_INVITE_SENT"

#define IS_IPAD (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad)
#define IS_IPHONE (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPhone)
#define IS_RETINA ([[UIScreen mainScreen] scale] >= 2.0)

#define SCREEN_WIDTH ([[UIScreen mainScreen] bounds].size.width)
#define SCREEN_HEIGHT ([[UIScreen mainScreen] bounds].size.height)
#define SCREEN_MAX_LENGTH (MAX(SCREEN_WIDTH, SCREEN_HEIGHT))
#define SCREEN_MIN_LENGTH (MIN(SCREEN_WIDTH, SCREEN_HEIGHT))

#define IS_IPHONE_4_OR_LESS (IS_IPHONE && SCREEN_MAX_LENGTH < 568.0)
#define IS_IPHONE_5 (IS_IPHONE && SCREEN_MAX_LENGTH == 568.0)
#define IS_IPHONE_6 (IS_IPHONE && SCREEN_MAX_LENGTH == 667.0)
#define IS_IPHONE_6P (IS_IPHONE && SCREEN_MAX_LENGTH == 736.0)
#define IS_IPHONE_SMALL_WIDTH (IS_IPHONE_4_OR_LESS || IS_IPHONE_5)

typedef enum{
    AppPlanTypeSure = 0,
    AppPlanTypeIf = 1,
    AppPlanTypeUpdate = 2
}
AppPlanType;


